/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tourify.View;

/**
 *
 * @author lenevo
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationBar = new javax.swing.JPanel();
        bookingsButton = new javax.swing.JButton();
        tourPackageButton = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));

        bookingsButton.setText("Bookings");
        bookingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsButtonMouseClicked(evt);
            }
        });

        tourPackageButton.setText("Tour Packages");
        tourPackageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tourPackageButtonMouseClicked(evt);
            }
        });
        tourPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourPackageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationBarLayout = new javax.swing.GroupLayout(navigationBar);
        navigationBar.setLayout(navigationBarLayout);
        navigationBarLayout.setHorizontalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tourPackageButton)
                    .addComponent(bookingsButton))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        navigationBarLayout.setVerticalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(bookingsButton)
                .addGap(60, 60, 60)
                .addComponent(tourPackageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.setPreferredSize(new java.awt.Dimension(100, 1024));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        BookingsDashboard1 bDashboard = new BookingsDashboard1();
        TourPackageDashboard tpDashboard = new TourPackageDashboard();
        tabPanel.add(bDashboard);
        tabPanel.add(tpDashboard);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(0);  
    }//GEN-LAST:event_bookingsButtonMouseClicked

    private void tourPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourPackageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tourPackageButtonActionPerformed

    private void tourPackageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tourPackageButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(1);  
    }//GEN-LAST:event_tourPackageButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            MainApp.util.logging.Logger.getLogger(MainApp.class.getName()).log(MainApp.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            MainApp.util.logging.Logger.getLogger(MainApp.class.getName()).log(MainApp.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            MainApp.util.logging.Logger.getLogger(MainApp.class.getName()).log(MainApp.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            MainApp.util.logging.Logger.getLogger(MainApp.class.getName()).log(MainApp.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        MainApp.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingsButton;
    private javax.swing.JPanel navigationBar;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JButton tourPackageButton;
    // End of variables declaration//GEN-END:variables
}
