/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tourify.View;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.swing.ImageIcon;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static tourify.Controller.Tour_PackageDao.DeleteTour_package;
import static tourify.Controller.Tour_PackageDao.UpdateTour_package;
import static tourify.Controller.Tour_PackageDao.addTourPackage;
import static tourify.Controller.Tour_PackageTable.getPictures;

import static tourify.Controller.Tour_PackageTable.getTourPackageNames;
import tourify.Model.Tour_Package;

/**
 *
 * @author lenevo
 */
public class TourPackageDashboard extends javax.swing.JPanel {

    public String itineraryPath = "";
    public String pamphletPath = "";
    public byte[] itineraryByte = new byte[0];
    public byte[] pamphletByte = new byte[0];

    /**
     * Creates new form TourPackageDashboard
     */
    public static BufferedImage convertByteArrayToImage(byte[] imageBytes) throws IOException {
        ByteArrayInputStream bais = new ByteArrayInputStream(imageBytes);
        return ImageIO.read(bais);
    }

    public TourPackageDashboard() {
        initComponents();
    }

    public void emptyFields() {
        packageField.setText("");
        noOfNightsFields.setText("");
        flightPriceField.setText("");
        queenPrice.setText("");
        twinPrice.setText("");
        destinationField.setText("");
        busField.setText("");
        packagePriceField.setText("");
        hotelContactField.setText("");

        phampletLabel.setIcon(null);
        itineraryLabel.setIcon(null);
    }

    public static byte[] pngToByte(String inputPath) {
        byte[] outputByte = new byte[0];

        try {
            Path path = Paths.get(inputPath);
            outputByte = Files.readAllBytes(path);

        } catch (IOException e) {
            System.err.println("IOException: " + e.getMessage());

        }
        return outputByte;
    }

    public static BufferedImage convertToBufferedImage(byte[] imageData) throws IOException {
        ByteArrayInputStream bis = new ByteArrayInputStream(imageData);
        return ImageIO.read(bis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deselectButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel Nights = new javax.swing.JLabel();
        packageField = new javax.swing.JTextField();
        noOfNightsFields = new javax.swing.JTextField();
        javax.swing.JLabel Hcontact = new javax.swing.JLabel();
        javax.swing.JLabel Package = new javax.swing.JLabel();
        packagePriceField = new javax.swing.JTextField();
        javax.swing.JLabel Tsizebed = new javax.swing.JLabel();
        javax.swing.JLabel Fprice = new javax.swing.JLabel();
        javax.swing.JLabel Bstop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        busField = new javax.swing.JTextField();
        javax.swing.JLabel Dname = new javax.swing.JLabel();
        queenPrice = new javax.swing.JTextField();
        hotelContactField = new javax.swing.JTextField();
        javax.swing.JLabel Qbed = new javax.swing.JLabel();
        flightPriceField = new javax.swing.JTextField();
        twinPrice = new javax.swing.JTextField();
        destinationField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JButton addItenary = new javax.swing.JButton();
        javax.swing.JButton viewPhamplet = new javax.swing.JButton();
        itineraryLabel = new javax.swing.JLabel();
        phampletLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpTable = new javax.swing.JTable();

        addButton.setBackground(new java.awt.Color(0, 102, 102));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/add.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(0, 102, 102));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/delete.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(0, 102, 102));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/updates.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        deselectButton.setBackground(new java.awt.Color(0, 102, 102));
        deselectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/choice.png"))); // NOI18N
        deselectButton.setText("Deselect");
        deselectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deselectButtonMouseClicked(evt);
            }
        });
        deselectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(deselectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, deleteButton, deselectButton, updateButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(deselectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Nights.setText("No of Nights");

        packageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageFieldActionPerformed(evt);
            }
        });

        noOfNightsFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfNightsFieldsActionPerformed(evt);
            }
        });

        Hcontact.setText("Hotel Contact");

        Package.setText("Package Name");

        packagePriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagePriceFieldActionPerformed(evt);
            }
        });

        Tsizebed.setText("Twin Size Bed Room Price");

        Fprice.setText("Flight Price");

        Bstop.setText("Bus Price");

        jLabel1.setText("Package Price");

        busField.setToolTipText("");
        busField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busFieldActionPerformed(evt);
            }
        });

        Dname.setText("Destination Name");

        hotelContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelContactFieldActionPerformed(evt);
            }
        });

        Qbed.setText("Queen Sized Bed Room Price");

        flightPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightPriceFieldActionPerformed(evt);
            }
        });

        twinPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twinPriceActionPerformed(evt);
            }
        });

        destinationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(packageField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfNightsFields)
                    .addComponent(flightPriceField)
                    .addComponent(Qbed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Package, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queenPrice))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotelContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(packagePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(Bstop, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(Hcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(Tsizebed, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {busField, destinationField, hotelContactField, twinPrice});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Package, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packagePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packageField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bstop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nights, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfNightsFields, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hcontact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Fprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotelContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qbed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tsizebed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queenPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        addItenary.setBackground(new java.awt.Color(0, 102, 102));
        addItenary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/adddd.png"))); // NOI18N
        addItenary.setText("Add Itineary");
        addItenary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItenaryActionPerformed(evt);
            }
        });

        viewPhamplet.setBackground(new java.awt.Color(0, 102, 102));
        viewPhamplet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourify/View/big view.png"))); // NOI18N
        viewPhamplet.setText("View Phamplates ");
        viewPhamplet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPhampletActionPerformed(evt);
            }
        });

        itineraryLabel.setBackground(new java.awt.Color(255, 255, 255));
        itineraryLabel.setForeground(new java.awt.Color(255, 255, 255));
        itineraryLabel.setText(" ");

        phampletLabel.setBackground(new java.awt.Color(255, 255, 255));
        phampletLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItenary, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPhamplet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(itineraryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phampletLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itineraryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addItenary, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phampletLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewPhamplet, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        try{
            tpTable.setModel(new DefaultTableModel(getTourPackageNames(),new String[] {"ID","Package","Destination","Package Price","Night NO","Bus Price","Flight Price","Hotel Contact","Twin Price","Queen Price"})
                {
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                });
            }catch(SQLException e){
                e.printStackTrace();
                tpTable.setModel(new DefaultTableModel(new Object[][]{},new String[] {"ID","Package","Destination","Package Price","Night NO","Bus Price","Flight Price","Hotel Contact","Twin Price","Queen Price"}));
            }
            tpTable.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tpTableMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tpTable);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 606, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(218, 218, 218))
            );
        }// </editor-fold>//GEN-END:initComponents

    private void noOfNightsFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfNightsFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfNightsFieldsActionPerformed

    private void flightPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightPriceFieldActionPerformed

    private void busFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busFieldActionPerformed

    private void twinPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twinPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twinPriceActionPerformed

    private void viewPhampletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPhampletActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif", "bmp");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        pamphletPath = f.getAbsolutePath();

        ImageIcon imageIcon = new ImageIcon(pamphletPath);
        Image resizedImage = imageIcon.getImage().getScaledInstance(335, 129, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        phampletLabel.setIcon(resizedIcon);
        pamphletByte = pngToByte(pamphletPath);

    }//GEN-LAST:event_viewPhampletActionPerformed

    private void addItenaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItenaryActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif", "bmp");
        chooser.setFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        itineraryPath = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(itineraryPath);
        Image resizedImage = imageIcon.getImage().getScaledInstance(335, 129, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        itineraryLabel.setIcon(resizedIcon);
        itineraryByte = pngToByte(itineraryPath);


    }//GEN-LAST:event_addItenaryActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel) tpTable.getModel();
        int selectedRow = tpTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a row first.", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int id = Integer.parseInt(tModel.getValueAt(tpTable.getSelectedRow(), 0).toString());
            try {
                DeleteTour_package(id);
            } catch (SQLException ex) {
                Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            emptyFields();
            try {
                tpTable.setModel(new DefaultTableModel(getTourPackageNames(), new String[]{"ID", "Package", "Destination", "Package Price", "Night NO", "Bus Price", "Flight Price", "Hotel Contact", "Twin Price", "Queen Price"}) {
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                }
                );
            } catch (SQLException ex) {
                Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            tpTable.clearSelection();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void destinationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_destinationFieldActionPerformed

    private void hotelContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelContactFieldActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked

        String packageName = packageField.getText();
        String destination = destinationField.getText();
        String hotelphone = hotelContactField.getText();

        if (packageName.equals("")
                || destination.equals("")
                || hotelphone.equals("")
                || noOfNightsFields.getText().equals("")
                || flightPriceField.getText().equals("")
                || queenPrice.getText().equals("")
                || twinPrice.getText().equals("")
                || busField.getText().equals("")
                || packagePriceField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insufficient credentials.", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else if (hotelContactField.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Hotel contact must be of ten digits", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int noOfNights = Integer.parseInt(noOfNightsFields.getText());
            int flightPrice = Integer.parseInt(flightPriceField.getText());
            int queenPricing = Integer.parseInt(queenPrice.getText());
            int twinPricing = Integer.parseInt(twinPrice.getText());
            int busPrice = Integer.parseInt(busField.getText());
            int packagePrice = Integer.parseInt(packagePriceField.getText());

            Tour_Package newtourpackage = new Tour_Package(packageName, destination, packagePrice, noOfNights, itineraryByte,
                    pamphletByte, busPrice, flightPrice, hotelphone,
                    twinPricing, queenPricing);
            try {
                addTourPackage(newtourpackage);
                emptyFields();
            } catch (SQLException ex) {
                Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                tpTable.setModel(new DefaultTableModel(getTourPackageNames(), new String[]{"ID", "Package", "Destination", "Package Price", "Night NO", "Bus Price", "Flight Price", "Hotel Contact", "Twin Price", "Queen Price"}) {
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                }
                );
            } catch (SQLException ex) {
                Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            tpTable.clearSelection();
            emptyFields();
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_addButtonMouseClicked

    private void packagePriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagePriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packagePriceFieldActionPerformed

    private void packageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageFieldActionPerformed

    private void deselectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectButtonActionPerformed

    }//GEN-LAST:event_deselectButtonActionPerformed

    private void tpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel) tpTable.getModel();
        int id = Integer.parseInt(tModel.getValueAt(tpTable.getSelectedRow(), 0).toString());

        packageField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 1));
        noOfNightsFields.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 4));
        flightPriceField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 6));
        queenPrice.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 9));
        twinPrice.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 8));
        destinationField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 2));
        busField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 5));
        packagePriceField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 3));
        hotelContactField.setText((String) tModel.getValueAt(tpTable.getSelectedRow(), 7));
        try {
            byte[][] pictures = getPictures(id);
            Image itinerary = convertByteArrayToImage(pictures[0]).getScaledInstance(335, 129, Image.SCALE_SMOOTH);
            Image pamphlet = convertByteArrayToImage(pictures[1]).getScaledInstance(335, 129, Image.SCALE_SMOOTH);
            itineraryLabel.setIcon(new ImageIcon(itinerary));
            phampletLabel.setIcon(new ImageIcon(pamphlet));
        } catch (SQLException ex) {
            Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tpTableMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked

        // TODO add your handling code here:
        int selectedRow = tpTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a row first", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (packageField.getText().equals("")
                    || destinationField.getText().equals("")
                    || hotelContactField.getText().equals("")
                    || noOfNightsFields.getText().equals("")
                    || flightPriceField.getText().equals("")
                    || queenPrice.getText().equals("")
                    || twinPrice.getText().equals("")
                    || busField.getText().equals("")
                    || packagePriceField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Insufficient credentials.", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else if (hotelContactField.getText().length() != 10) {
                JOptionPane.showMessageDialog(null, "Hotel contact must be of ten digits", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String packageName = packageField.getText();
                int noOfNights = Integer.parseInt(noOfNightsFields.getText());
                int flightPrice = Integer.parseInt(flightPriceField.getText());
                int queenPricing = Integer.parseInt(queenPrice.getText());
                int twinPricing = Integer.parseInt(twinPrice.getText());
                String destination = destinationField.getText();
                int busPrice = Integer.parseInt(busField.getText());
                int packagePrice = Integer.parseInt(packagePriceField.getText());
                String hotelphone = hotelContactField.getText();

                DefaultTableModel tModel = (DefaultTableModel) tpTable.getModel();
                int id = Integer.parseInt(tModel.getValueAt(tpTable.getSelectedRow(), 0).toString());

                Tour_Package newtourpackage = new Tour_Package(packageName, destination, packagePrice, noOfNights, itineraryByte,
                        pamphletByte, busPrice, flightPrice, hotelphone,
                        twinPricing, queenPricing);
                try {
                    UpdateTour_package(newtourpackage, id);
                    emptyFields();
                } catch (SQLException ex) {
                    Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    tpTable.setModel(new DefaultTableModel(getTourPackageNames(), new String[]{"ID", "Package", "Destination", "Package Price", "Night NO", "Bus Price", "Flight Price", "Hotel Contact", "Twin Price", "Queen Price"}) {
                        public boolean isCellEditable(int row, int column) {
                            return false;
                        }
                    }
                    );
                } catch (SQLException ex) {
                    Logger.getLogger(TourPackageDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
                tpTable.clearSelection();
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void deselectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deselectButtonMouseClicked

        emptyFields();
        tpTable.clearSelection();
    }//GEN-LAST:event_deselectButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField busField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deselectButton;
    private javax.swing.JTextField destinationField;
    private javax.swing.JTextField flightPriceField;
    private javax.swing.JTextField hotelContactField;
    private javax.swing.JLabel itineraryLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noOfNightsFields;
    private javax.swing.JTextField packageField;
    private javax.swing.JTextField packagePriceField;
    private javax.swing.JLabel phampletLabel;
    private javax.swing.JTextField queenPrice;
    private javax.swing.JTable tpTable;
    private javax.swing.JTextField twinPrice;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
